# This file was generated by GoReleaser. DO NOT EDIT.
class Undocker < Formula
  desc "a tool for decomposing docker images."
  homepage "https://github.com/tokibi/undocker/"
  url "https://github.com/tokibi/undocker/releases/download/v0.1.1/undocker_0.1.1_darwin_amd64.tar.gz"
  version "0.1.1"
  sha256 "59ecd8732751dd8a0441cf4c718f64925ed0264c13b4e2125fcd37dd1350a196"

  def install
    bin.install "undocker"
  end

  test do
    system "#{bin}/undocker --version"
  end
end
