# This file was generated by GoReleaser. DO NOT EDIT.
class Undocker < Formula
  desc "a tool for decomposing docker images."
  homepage "https://github.com/tokibi/undocker/"
  url "https://github.com/tokibi/undocker/releases/download/v0.1.7/undocker_0.1.7_darwin_amd64.tar.gz"
  version "0.1.7"
  sha256 "4987bf9baeb990f76e83359edd87bd0fe2565cd856274a4f99a2092b2ac90ee1"

  def install
    bin.install "undocker"
  end

  test do
    system "#{bin}/undocker --version"
  end
end
